// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cpkkcdzbmkazkyuzxogl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNwa2tjZHpibWthemt5dXp4b2dsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIwMzg0MDUsImV4cCI6MjA2NzYxNDQwNX0.IyHdMbhaxIuVKffndDNBgmpJdJ9D6L76Zk47WdQOX7I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});